import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SideBar from "@/components/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
     
        <Navbar/>
        <div className="grid bg-gray-900 grid-cols-1 sm:grid-cols-[300px,1fr]">
          <SideBar/>
          {children}
        </div>
        </body>
    </html>
  );
}
